/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SS_aliases.h"
#include "SS.h"
#include "UART_tester.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "SPIS_1.h"
#include "SPIS_1_PVT.h"
#include "LED_aliases.h"
#include "LED.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "isr_1.h"
#include "Pin_A1_aliases.h"
#include "Pin_A1.h"
#include "Pin_A2_aliases.h"
#include "Pin_A2.h"
#include "Pin_B1_aliases.h"
#include "Pin_B1.h"
#include "Pin_B2_aliases.h"
#include "Pin_B2.h"
#include "Motor_Calibration_Sensor_aliases.h"
#include "Motor_Calibration_Sensor.h"
#include "Pill_Container_Sensor_aliases.h"
#include "Pill_Container_Sensor.h"
#include "RPI_INT_aliases.h"
#include "RPI_INT.h"
#include "Pin_C1_aliases.h"
#include "Pin_C1.h"
#include "Pin_C2_aliases.h"
#include "Pin_C2.h"
#include "Pin_D1_aliases.h"
#include "Pin_D1.h"
#include "Pin_D2_aliases.h"
#include "Pin_D2.h"
#include "UART_tester_IntClock.h"
#include "SPIS_1_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

